config/routes.rb
Christmasforvets::Application.routes.draw do

  
  root  'static_pages#home'
  
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/start',   to: 'static_pages#start',   via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  
  

  
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end
  
  def start
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Christmas for Vets"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<br>
<br>


<!-- FOOTER -->
<div class="container">
<hr>
	<footer>
		
    </footer>
</div>

app/views/layouts/_header.html.erb
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" <%= link_to "Christmas for Vets", root_path %></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Christmas for Vets">
    <meta name="author" content="Garrett">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/header' %>
  <body>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      <div class="container">
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<br>
<br>
<br>
<br>
<br>
<br>


<div class="container">

	<h2 class="title"><a href="#">Military Donation</a></h2>
	<p class="mytext">This Christmas holiday we want to make a donation to our military. We appreciate all that that they have done for our country, this Christmas we want to give back by donating 100% of the profits made from our tee-shirt sales.</p>
	<br>
	<hr>
	<h2 class="title"><a href="http://teespring.com/">TeeSpring</a></h2>
	<p class="mytext">Our tee-shirt's will me</p>
	<br>
	<hr>
	<center><h2 class="teamtitle">The Team</h2></center>
	
<!-- Meet the team -->

<center>

	
	<ul class="list-inlinec">
		<li>
          <%= link_to image_tag("garrett.png", alt: "Garrett"), 'http://www.linkedin.com/pub/garrett-cura/40/674/526' %>
          <h2 class="title">Garrett</h2>
          <p class="mytext">Hi! I'm Garrett...</p>
		</li>
		
		
		<li>
          <%= link_to image_tag("austin.jpg", alt: "Austin")%>
          <h2 class="title">Austin</h2>
          <p class="mytext">Hi! I'm Austin...</p>
		</li>
		
	</ul>
	
</center>		  
        
      
</div>

app/views/static_pages/contact.html.erb
<br>
<br>
<br>
<br>
<br>
<br>


<div class="container">
<center><h1>Contact Us</h1>

<br>
<br>

<p>Feel free to contact us at christmasforvets@gmail.com with any questions or concerns</p>



</center>




</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!-- Carousel================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
            <div class="carousel-inner">
        <div class="item active">
        <%= link_to image_tag("1.jpg", alt: "Sorry cant find image :(")%>
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel1">Welcome to Christmas for Vets!</h1>
              <p></p>
              <a class="btn btn-lg btn-success" href="http://teespring.com" role="button">Order your T-Shirt Today!</a>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
        <%= link_to image_tag("2.jpg", alt: "Sorry cant find image :(")%>
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel2"><%= link_to "Learn", about_path %> About What We Support</h1>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
        <%= link_to image_tag("3.jpg", alt: "Sorry cant find image :(")%>
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel3"><%= link_to "Learn", start_path %> How to Start!</h1>
              <p></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="#"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="#"></span></a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <center><h1><span id="countdown"></span></h1></center>
    <script>
    // set the date we're counting down to
    var target_date = new Date("Dec 11, 2013").getTime();
 
    // variables for time units
    var days, hours, minutes, seconds;
 
    // get tag element
    var countdown = document.getElementById("countdown");
 
    // update the tag with id "countdown" every 1 second
    setInterval(function () {
 
    // find the amount of "seconds" between now and target
    var current_date = new Date().getTime();
    var seconds_left = (target_date - current_date) / 1000;
 
    // do some time calculations
    days = parseInt(seconds_left / 86400);
    seconds_left = seconds_left % 86400;
     
    hours = parseInt(seconds_left / 3600);
    seconds_left = seconds_left % 3600;
     
    minutes = parseInt(seconds_left / 60);
    seconds = parseInt(seconds_left % 60);
     
    // format countdown string + set tag value
    countdown.innerHTML = days + " Days, " + hours + " Hours, "
    + minutes + " Minutes, " + seconds + " Seconds";  
 
    }, 1000);
    </script>


    <div class="container marketing">

      <!-- START THE FEATURETTES -->


      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><a href="http://www.woundedwarriorproject.org">Wounded Warriors.</a><span class="text-muted">Some Other Text.</span></h2>
          <p class="lead">Talk about wounded warriors and why it is good to help them .</p>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("attention1.jpg", alt: "Sorry cant find image :(")%>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <%= link_to image_tag("attention2.jpg", alt: "Sorry cant find image :(")%>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Donating 100% of Profits. <span class="text-muted">Some Other Text.</span></h2>
          <p class="lead">Talk about how we are giving 100% of our profits away.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Support our Troops. <span class="text-muted">Some Other Text.</span></h2>
          <p class="lead">Talk about 100% percent American made etc.</p>
          <a class="btn btn-lg btn-success" href="http://teespring.com" role="button">Order your T-Shirt Today!</a>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("attention3.jpg", alt: "Sorry cant find image :(")%>
        </div>
      </div>


      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->
    
    